rename workflow, put fail test first and remove continue if fail

diff --git a/.github/workflows/2d_Unit_Tests.yaml b/.github/workflows/2d_Unit_Tests.yaml
--- a/.github/workflows/2d_Unit_Tests.yaml
+++ b/.github/workflows/2d_Unit_Tests.yaml
@@ -1,4 +1,4 @@
-name: Check Tests
+name: 2d Unit Tests
 
 on: [push, pull_request]
 
@@ -11,13 +11,12 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
+    - name: check fail file
+      run: |
+        echo "Testing Fail condition"
+        if [[ $(cat $(git rev-parse --show-toplevel)/src/tests/test-testF-results.txt) == "fail" ]]; then exit 1 ; fi        
     - name: check pass file
-      continue-on-error: true
       run: | 
         echo "Testing Pass condition"
         if [[ $(cat $(git rev-parse --show-toplevel)/src/tests/test-testP-results.txt) == "pass" ]]; then exit 0 ; fi
-    - name: check fail file
-      continue-on-error: true
-      run: |
-        echo "Testing Fail condition"
-        if [[ $(cat $(git rev-parse --show-toplevel)/src/tests/test-testF-results.txt) == "fail" ]]; then exit 1 ; fi
+
